# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 86e0e6202cb6fc45887c35b75758c2e41274ac94548405817970fa6cccf1c4ea54ecf5eb5eb1bb1465c126d23da74952af03421f0a6d348f4cc73d397ad05c8b

test:
  secret_key_base: 143667f6cae541732640a01b971e094bea5398155a561ea4a2d24bf120bbdd873485af64bfcdf6ffb86f790895e8f0a8b379119e3cc3a34608347d14e5d0f4f7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
